services:
    backend:
        build:
            context: .
            dockerfile: ./apps/backend/Dockerfile
        hostname: backend
        environment:
            - WEBSOCKET_PORT=8080

    frontend:
        build:
            context: .
            dockerfile: ./apps/frontend/Dockerfile
        hostname: frontend
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_WEBSOCKET_URI=ws://backend:8080

    playwright:
        build:
            context: .
            dockerfile: ./apps/frontend/Dockerfile.playwright
        depends_on:
            - frontend
            - backend
        environment:
            - PLAYWRIGHT_BASE_URL=http://frontend:3000
            - CI=true
        volumes:
            # Mount volumes to get the test reports out of the container and onto the
            # GitHub Actions runner, so they can be uploaded as artifacts.
            - ./apps/frontend/playwright-report:/usr/src/app/apps/frontend/playwright-report
            - ./apps/frontend/test-results:/usr/src/app/apps/frontend/test-results