name: "CI & E2E Tests"

on:
    push:
        branches: ["main", "dev"]
    pull_request:
        branches: ["main", "dev"]

jobs:
    test:
        name: "Run End-to-End Tests"
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4

            - name: "Set up Docker Buildx"
              uses: docker/setup-buildx-action@v3

            - name: "Build and Run Services"
              run: docker-compose -f docker-compose.ci.yml build

            - name: "Run Playwright Tests"
              run: |
                  # This command starts all services and waits for the 'playwright' container to exit.
                  # It then propagates the exit code from 'playwright'. If tests fail (non-zero exit code),
                  # this step will fail, causing the entire workflow to fail.
                  # It also automatically shuts down all services afterwards.
                  docker-compose -f docker-compose.ci.yml up --exit-code-from playwright --abort-on-container-exit

            - name: "Upload Playwright Report"
                # This step runs even if the tests fail, so you can always see the report.
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: ./apps/frontend/playwright-report/
                  retention-days: 7